#!/usr/bin/env python3
"""check-all — run every layer scoreboard, L7 down to L0 (the book's reading order).

Exit code is nonzero iff any layer reported a FAIL. Pass --list to print the
obligation census without running anything, or --md to emit the scoreboard as a
markdown book page (what CI embeds into the rendered book as an appendix).
"""
import datetime
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ORDER = [7, 6, 5, 4, 3, 2, 1, 0]

if "--md" in sys.argv[1:]:
    try:
        commit = subprocess.run(["git", "rev-parse", "--short", "HEAD"], cwd=HERE,
                                capture_output=True, text=True).stdout.strip() or "unknown"
    except OSError:
        commit = "unknown"
    date = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    print("# Scoreboard — checker results\n")
    print(f"Generated by `tools/check-all.py --md` from commit `{commit}` on {date}, "
          "against the flow-generated artifacts of [data provenance](data-provenance.md) — the same "
          "run that built this book. Every obligation the book states appears exactly "
          "once; the [README](https://github.com/digama0/thinking-sand#the-layer-scoreboards--toolscheck-l0py--check-l7py) "
          "documents the suite.\n")
    print("**PASS** — the check ran and the obligation holds of the generated artifacts. "
          "**FINDING** — the check ran and confirms an adverse fact recorded in "
          "[Findings](findings.md) (expected). **FAIL** — the shipped data contradicts "
          "the record; a bug in artifact, record, or checker. **TODO** — not yet "
          "checkable; the stub names its blocker. **EXTERN** — axiom-register material "
          "no program over shipped data can reach.\n")

rc = 0
for n in ORDER:
    r = subprocess.run([sys.executable, str(HERE / f"check-l{n}.py"), *sys.argv[1:]])
    rc |= r.returncode
    if "--md" not in sys.argv[1:]:
        print()
sys.exit(rc)
