#!/usr/bin/env bash
# run-flow.sh — run the FULL RTL-to-GDS pipeline on the target core.
#
# This is the "generate silicon from the 2026 plans" path. It takes the pinned
# target core (data/mgmt/VexRiscv_target.v, itself regenerated by
# tools/regenerate-core.sh) through synthesis, floorplanning, placement, CTS,
# routing, extraction, multi-corner STA, DRC and LVS — producing a GDS and a
# nine-corner signoff table that we generated rather than fetched.
#
# The flow is librelane (the OpenLane 2 successor), installed as one
# self-contained AppImage by tools/install-toolchain.sh --only flow. It runs
# under bubblewrap because the AppImage's FUSE self-mount is unavailable in most
# sandboxes; librelane-shell (written by the installer) wraps that.
#
# The PDK is librelane's own ciel-fetched sky130A, NOT the 2020 open_pdks build
# the 2021 chip used: that build predates configuration variables librelane 3.x
# requires (PDN_VPITCH and friends), so it cannot drive this flow. Pinning the
# 2026 core means pinning a 2026-compatible PDK with it.
#
# NOTE on ERROR_ON_SYNTH_CHECKS: the target core contains four undriven
# signals, and the flow's own synthesis checker refuses to proceed on them by
# default. Two are long-standing (instruction-cache inputs, present in the 2021
# core too); two are a 2026 generator REGRESSION — CsrPlugin_mtvec_mode, which
# the 2021 core drives and this one does not. All four are provably inert (see
# findings), so the config disables the checker and the fact is recorded rather
# than the design being silently patched.
#
# Usage: tools/run-flow.sh [pdk-root]      (default /tmp/pdk2; ~35 min)
set -euo pipefail
cd "$(dirname "$0")/.."
PDK_ROOT="${1:-/tmp/pdk2}"
RUN=rtl2gds

command -v librelane-shell >/dev/null || {
  echo "librelane-shell not found — tools/install-toolchain.sh --only flow" >&2; exit 1; }
[ -s data/mgmt/VexRiscv_target.v ] || {
  echo "no target core — run tools/regenerate-core.sh first" >&2; exit 1; }

cp data/mgmt/VexRiscv_target.v flow/vexriscv/
mkdir -p "$PDK_ROOT"
rm -rf "flow/vexriscv/runs/$RUN"

echo "== running the full flow (synthesis -> GDS -> signoff); this takes ~35 min"
librelane-shell librelane --pdk-root "$PDK_ROOT" --pdk sky130A \
  --run-tag "$RUN" flow/vexriscv/config.json

exec python3 tools/flowreport.py "flow/vexriscv/runs/$RUN"
